import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786045689224 implements MigrationInterface {
    name = 'InitialSchema1786045689224'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "system" ("id" SERIAL NOT NULL, "termsAndConditions" text, "privacyPolicy" text, "aboutUs" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b1e6b6f88da9888fde62379945" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit" ("id" SERIAL NOT NULL, "action" character varying NOT NULL, "comment" character varying NOT NULL, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "PK_1d3d120ddaf7bc9b1ed68ed463a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status_supportid" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, CONSTRAINT "PK_35f185a029d72a1c92a0bbe633c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment_supportid" ("id" SERIAL NOT NULL, "comment" text NOT NULL, "processedBy" integer, "processedAt" TIMESTAMP, "rejectReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, "statusId" integer, CONSTRAINT "PK_970a56d8043b51a15a9f01c581b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_status" ("id" SERIAL NOT NULL, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_565cc1bce0e40e09ff1b62b7778" UNIQUE ("status"), CONSTRAINT "PK_b20867e84903dbaf5390a0a8ee3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_message" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8650617cb9caae9dc43d872a900" UNIQUE ("type"), CONSTRAINT "PK_9103fef9f841c497d94f93afe77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_chat" ("id" SERIAL NOT NULL, "message" text NOT NULL, "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "chatId" integer NOT NULL, "typeId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_859ffc7f95098efb4d84d50c632" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_chat" ("id" SERIAL NOT NULL, "donator" boolean NOT NULL DEFAULT false, "admin" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "chatId" integer NOT NULL, CONSTRAINT "PK_c43d9c7669f5c12f23686e1b891" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat" ("id" SERIAL NOT NULL, "chatName" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "chatStatusId" integer NOT NULL, "donationId" integer, CONSTRAINT "REL_4f9a28f3875b7d615e3aa9771d" UNIQUE ("donationId"), CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donation_review" ("id" SERIAL NOT NULL, "review" text NOT NULL, "raiting" integer NOT NULL, "userId" integer NOT NULL, "donationId" integer NOT NULL, CONSTRAINT "PK_3fcd1455517ebb00859f6328115" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "image_post" ("id" SERIAL NOT NULL, "image" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" integer NOT NULL, CONSTRAINT "PK_595c60d3e7e8edf1cc0912782bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_article" ("id" SERIAL NOT NULL, "cant" integer NOT NULL DEFAULT '1', "needed" boolean NOT NULL DEFAULT false, "userId" integer, "articleId" integer, CONSTRAINT "PK_38769eee16dab07c432832611f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "descripcion" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40808690eb7b915046558c0f81b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_article_donation" ("id" SERIAL NOT NULL, "quantity" character varying NOT NULL DEFAULT '1', "donationId" integer NOT NULL, "postArticleId" integer NOT NULL, CONSTRAINT "PK_dfbd88cd106aef3d3c7e6d7b98b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status_post_donation_article" ("id" SERIAL NOT NULL, "status" character varying NOT NULL, CONSTRAINT "PK_a858d8abcbf1ef5bb1ce4f0870f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_article" ("id" SERIAL NOT NULL, "quantity" character varying NOT NULL DEFAULT '1', "articleId" integer NOT NULL, "postId" integer NOT NULL, "statusId" integer NOT NULL, CONSTRAINT "PK_7ca33a06ae7d42cf3563c20bf46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_liked" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_54c0df168b71df765b2ee9701ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tag" ("id" SERIAL NOT NULL, "tag" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9dbf61b2d00d2c77d3b5ced37c6" UNIQUE ("tag"), CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_tags" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_0c750579b992a52b24d18ec3431" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_post" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_896a73360c4f47d3aea0787ab08" UNIQUE ("type"), CONSTRAINT "PK_49ed7b84d4009170f92144030bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "typePostId" integer, CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status_donation" ("id" SERIAL NOT NULL, "status" character varying(50) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cbe8e098da3d7d3e3597b6de253" UNIQUE ("status"), CONSTRAINT "PK_b234714c67f3d2bda7744c27036" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donation" ("id" SERIAL NOT NULL, "lugarRecogida" character varying, "lugarDonacion" character varying, "comments" json, "fechaMaximaEntrega" date, "incrementDate" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postId" integer NOT NULL, "userId" integer NOT NULL, "statusDonationId" integer, CONSTRAINT "PK_25fb5a541964bc5cfc18fb13a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_dni" ("id" SERIAL NOT NULL, "type" character varying(50) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0c3079f3b5e4b7adac9eec10e73" UNIQUE ("type"), CONSTRAINT "PK_e6f215e43f9d1a1f0b81b64e3e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "people" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "municipio" character varying, "lastName" character varying, "birdthDate" date NOT NULL, "dni" character varying(15) NOT NULL, "residencia" character varying(100) NOT NULL, "telefono" character varying(10) NOT NULL, "supportId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "typeDniId" integer NOT NULL, CONSTRAINT "UQ_c18da65793895769252e363e34d" UNIQUE ("dni"), CONSTRAINT "UQ_23c0daa2f734154e93612be72db" UNIQUE ("telefono"), CONSTRAINT "PK_aa866e71353ee94c6cc51059c5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_report" ("id" SERIAL NOT NULL, "type" character varying(100) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_07845de6f147ec45bf5bbd67629" UNIQUE ("type"), CONSTRAINT "PK_8fb206e7dfaabe4c3656ffbaba4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report" ("id" SERIAL NOT NULL, "comments" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "typeReportId" integer NOT NULL, CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rol" ("id" SERIAL NOT NULL, "rol" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f75f91537c43db80c3ca8ef34f8" UNIQUE ("rol"), CONSTRAINT "PK_c93a22388638fac311781c7f2dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "type_notify" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d29fbd3bb6ba8bb0a7a32f5dabf" UNIQUE ("type"), CONSTRAINT "PK_790676b0088fd718d7441665b37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notify" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "message" character varying NOT NULL, "link" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "typeId" integer NOT NULL, CONSTRAINT "PK_27732ed6dd5bf6aad9afed59ec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_notify" ("id" SERIAL NOT NULL, "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "notifyId" integer NOT NULL, CONSTRAINT "PK_eee18952cce2715a3cc82485873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "username" character varying(100) NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "token" character varying, "loginAttempts" integer NOT NULL DEFAULT '0', "lockUntil" TIMESTAMP, "profilePhoto" character varying, "dateSendCodigo" TIMESTAMP, "lastLogin" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "verified" boolean NOT NULL DEFAULT false, "code" character varying, "block" boolean NOT NULL DEFAULT true, "location" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "peopleId" integer NOT NULL, "rolId" integer NOT NULL, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_e2e38b1d0096ee56deaa6d6f55" UNIQUE ("peopleId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_system" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer NOT NULL, "systemId" integer NOT NULL, CONSTRAINT "PK_d0612215c1ab17ba00b0153c339" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "audit" ADD CONSTRAINT "FK_7ae389e858ad6f2c0c63112e387" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_supportid" ADD CONSTRAINT "FK_f5a3f3cffa47c989bdcac381420" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_supportid" ADD CONSTRAINT "FK_113c8debac4443b9ffd1ec1126b" FOREIGN KEY ("statusId") REFERENCES "status_supportid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_chat" ADD CONSTRAINT "FK_3b796830468ad521180dfa750e4" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_chat" ADD CONSTRAINT "FK_3b730aa2601f56beba3154dea1b" FOREIGN KEY ("typeId") REFERENCES "type_message"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_chat" ADD CONSTRAINT "FK_a2ea0a69ecd3a1ea597aabe83e1" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_63f6e1b207375c35588c673843e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_chat" ADD CONSTRAINT "FK_e2f3a6eefb26aa957feee2c9dc3" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_b7be396ff3c2aa7925f17591da6" FOREIGN KEY ("chatStatusId") REFERENCES "chat_status"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_4f9a28f3875b7d615e3aa9771d8" FOREIGN KEY ("donationId") REFERENCES "donation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation_review" ADD CONSTRAINT "FK_fdaa353977bc2c82c61ceb0cf15" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation_review" ADD CONSTRAINT "FK_e4f6726052f32b829e772ddebdf" FOREIGN KEY ("donationId") REFERENCES "donation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_post" ADD CONSTRAINT "FK_f281885fcb084a21c32402a70aa" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_article" ADD CONSTRAINT "FK_63ce882421304284bba56f4bb9c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_article" ADD CONSTRAINT "FK_93fbc2fe83f6b786b5b1f5932dd" FOREIGN KEY ("articleId") REFERENCES "article"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_article_donation" ADD CONSTRAINT "FK_bc3b42ee1be6442093d8ff2cbe2" FOREIGN KEY ("donationId") REFERENCES "donation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_article_donation" ADD CONSTRAINT "FK_a0bc0a14f1d329d3d533e8cd454" FOREIGN KEY ("postArticleId") REFERENCES "post_article"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_article" ADD CONSTRAINT "FK_ab30c5f2c8146f708735dcf1c30" FOREIGN KEY ("articleId") REFERENCES "article"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_article" ADD CONSTRAINT "FK_e7121b1df0fd24f6aba87ab957e" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_article" ADD CONSTRAINT "FK_7fb6d457a85efaf1b3b351eb0e9" FOREIGN KEY ("statusId") REFERENCES "status_post_donation_article"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_liked" ADD CONSTRAINT "FK_148fc5f321296e090d3a1b2d902" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_liked" ADD CONSTRAINT "FK_9c3f3632e183731a6c7965b76e4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_tags" ADD CONSTRAINT "FK_76e701b89d9bba541e1543adfac" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_tags" ADD CONSTRAINT "FK_86fabcae8483f7cc4fbd36cf6a2" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_5c1cf55c308037b5aca1038a131" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post" ADD CONSTRAINT "FK_b7d25b3c62388db659a787b6eca" FOREIGN KEY ("typePostId") REFERENCES "type_post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_8c0e69c804a58b904037ee6a79d" FOREIGN KEY ("postId") REFERENCES "post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_063499388657e648418470a439a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_e7059765c27a3259f6fbc17d717" FOREIGN KEY ("statusDonationId") REFERENCES "status_donation"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "FK_c012be60ab404219b6957d99eb3" FOREIGN KEY ("typeDniId") REFERENCES "type_dni"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_e347c56b008c2057c9887e230aa" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_1151e01e1b797e2a5e0eed7ce03" FOREIGN KEY ("typeReportId") REFERENCES "type_report"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notify" ADD CONSTRAINT "FK_afdcd92b9d004658bdbdb5c1a6a" FOREIGN KEY ("typeId") REFERENCES "type_notify"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notify" ADD CONSTRAINT "FK_523de157e30f3ab59df42a1dfa3" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notify" ADD CONSTRAINT "FK_c8654c92e0f428a08dbe2c44e07" FOREIGN KEY ("notifyId") REFERENCES "notify"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_e2e38b1d0096ee56deaa6d6f559" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_f66058a8f024b32ce70e0d6a929" FOREIGN KEY ("rolId") REFERENCES "rol"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_system" ADD CONSTRAINT "FK_ee30c20b72a2e1af721a5b81b54" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_system" ADD CONSTRAINT "FK_f6112fbe73b817f67b6a65b8cba" FOREIGN KEY ("systemId") REFERENCES "system"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_system" DROP CONSTRAINT "FK_f6112fbe73b817f67b6a65b8cba"`);
        await queryRunner.query(`ALTER TABLE "user_system" DROP CONSTRAINT "FK_ee30c20b72a2e1af721a5b81b54"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_f66058a8f024b32ce70e0d6a929"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_e2e38b1d0096ee56deaa6d6f559"`);
        await queryRunner.query(`ALTER TABLE "user_notify" DROP CONSTRAINT "FK_c8654c92e0f428a08dbe2c44e07"`);
        await queryRunner.query(`ALTER TABLE "user_notify" DROP CONSTRAINT "FK_523de157e30f3ab59df42a1dfa3"`);
        await queryRunner.query(`ALTER TABLE "notify" DROP CONSTRAINT "FK_afdcd92b9d004658bdbdb5c1a6a"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_1151e01e1b797e2a5e0eed7ce03"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_e347c56b008c2057c9887e230aa"`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "FK_c012be60ab404219b6957d99eb3"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_e7059765c27a3259f6fbc17d717"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_063499388657e648418470a439a"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_8c0e69c804a58b904037ee6a79d"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_b7d25b3c62388db659a787b6eca"`);
        await queryRunner.query(`ALTER TABLE "post" DROP CONSTRAINT "FK_5c1cf55c308037b5aca1038a131"`);
        await queryRunner.query(`ALTER TABLE "post_tags" DROP CONSTRAINT "FK_86fabcae8483f7cc4fbd36cf6a2"`);
        await queryRunner.query(`ALTER TABLE "post_tags" DROP CONSTRAINT "FK_76e701b89d9bba541e1543adfac"`);
        await queryRunner.query(`ALTER TABLE "post_liked" DROP CONSTRAINT "FK_9c3f3632e183731a6c7965b76e4"`);
        await queryRunner.query(`ALTER TABLE "post_liked" DROP CONSTRAINT "FK_148fc5f321296e090d3a1b2d902"`);
        await queryRunner.query(`ALTER TABLE "post_article" DROP CONSTRAINT "FK_7fb6d457a85efaf1b3b351eb0e9"`);
        await queryRunner.query(`ALTER TABLE "post_article" DROP CONSTRAINT "FK_e7121b1df0fd24f6aba87ab957e"`);
        await queryRunner.query(`ALTER TABLE "post_article" DROP CONSTRAINT "FK_ab30c5f2c8146f708735dcf1c30"`);
        await queryRunner.query(`ALTER TABLE "post_article_donation" DROP CONSTRAINT "FK_a0bc0a14f1d329d3d533e8cd454"`);
        await queryRunner.query(`ALTER TABLE "post_article_donation" DROP CONSTRAINT "FK_bc3b42ee1be6442093d8ff2cbe2"`);
        await queryRunner.query(`ALTER TABLE "user_article" DROP CONSTRAINT "FK_93fbc2fe83f6b786b5b1f5932dd"`);
        await queryRunner.query(`ALTER TABLE "user_article" DROP CONSTRAINT "FK_63ce882421304284bba56f4bb9c"`);
        await queryRunner.query(`ALTER TABLE "image_post" DROP CONSTRAINT "FK_f281885fcb084a21c32402a70aa"`);
        await queryRunner.query(`ALTER TABLE "donation_review" DROP CONSTRAINT "FK_e4f6726052f32b829e772ddebdf"`);
        await queryRunner.query(`ALTER TABLE "donation_review" DROP CONSTRAINT "FK_fdaa353977bc2c82c61ceb0cf15"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_4f9a28f3875b7d615e3aa9771d8"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_b7be396ff3c2aa7925f17591da6"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_e2f3a6eefb26aa957feee2c9dc3"`);
        await queryRunner.query(`ALTER TABLE "user_chat" DROP CONSTRAINT "FK_63f6e1b207375c35588c673843e"`);
        await queryRunner.query(`ALTER TABLE "message_chat" DROP CONSTRAINT "FK_a2ea0a69ecd3a1ea597aabe83e1"`);
        await queryRunner.query(`ALTER TABLE "message_chat" DROP CONSTRAINT "FK_3b730aa2601f56beba3154dea1b"`);
        await queryRunner.query(`ALTER TABLE "message_chat" DROP CONSTRAINT "FK_3b796830468ad521180dfa750e4"`);
        await queryRunner.query(`ALTER TABLE "comment_supportid" DROP CONSTRAINT "FK_113c8debac4443b9ffd1ec1126b"`);
        await queryRunner.query(`ALTER TABLE "comment_supportid" DROP CONSTRAINT "FK_f5a3f3cffa47c989bdcac381420"`);
        await queryRunner.query(`ALTER TABLE "audit" DROP CONSTRAINT "FK_7ae389e858ad6f2c0c63112e387"`);
        await queryRunner.query(`DROP TABLE "user_system"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_notify"`);
        await queryRunner.query(`DROP TABLE "notify"`);
        await queryRunner.query(`DROP TABLE "type_notify"`);
        await queryRunner.query(`DROP TABLE "rol"`);
        await queryRunner.query(`DROP TABLE "report"`);
        await queryRunner.query(`DROP TABLE "type_report"`);
        await queryRunner.query(`DROP TABLE "people"`);
        await queryRunner.query(`DROP TABLE "type_dni"`);
        await queryRunner.query(`DROP TABLE "donation"`);
        await queryRunner.query(`DROP TABLE "status_donation"`);
        await queryRunner.query(`DROP TABLE "post"`);
        await queryRunner.query(`DROP TABLE "type_post"`);
        await queryRunner.query(`DROP TABLE "post_tags"`);
        await queryRunner.query(`DROP TABLE "tag"`);
        await queryRunner.query(`DROP TABLE "post_liked"`);
        await queryRunner.query(`DROP TABLE "post_article"`);
        await queryRunner.query(`DROP TABLE "status_post_donation_article"`);
        await queryRunner.query(`DROP TABLE "post_article_donation"`);
        await queryRunner.query(`DROP TABLE "article"`);
        await queryRunner.query(`DROP TABLE "user_article"`);
        await queryRunner.query(`DROP TABLE "image_post"`);
        await queryRunner.query(`DROP TABLE "donation_review"`);
        await queryRunner.query(`DROP TABLE "chat"`);
        await queryRunner.query(`DROP TABLE "user_chat"`);
        await queryRunner.query(`DROP TABLE "message_chat"`);
        await queryRunner.query(`DROP TABLE "type_message"`);
        await queryRunner.query(`DROP TABLE "chat_status"`);
        await queryRunner.query(`DROP TABLE "comment_supportid"`);
        await queryRunner.query(`DROP TABLE "status_supportid"`);
        await queryRunner.query(`DROP TABLE "audit"`);
        await queryRunner.query(`DROP TABLE "system"`);
    }

}
