FROM postgres:16-alpine

# Valores por defecto (se pueden sobrescribir con environment en docker-compose)
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=2005 \
    POSTGRES_DB=donarapp

EXPOSE 5432

VOLUME /var/lib/postgresql/data
